name: EC2 controller

on:
  workflow_dispatch:

jobs:
  ec2-command:
    name: EC2 controller
    runs-on: [ self-hosted ]

    steps:
      - name: Input Shell Command
        run: |
          ps aux | grep java
          sudo lsof -ti:80
