name: release-please (app only)

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'release-please-config.json'
      - '.release-please-manifest.json'
      - '.github/workflows/release-please.yml'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Release Please (manifest)
        uses: googleapis/release-please-action@v4
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
